/* Auto-generated by cbindgen — do not edit. */

#ifndef SNOREGUARD_CORE_H
#define SNOREGUARD_CORE_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#define FRAME_SIZE 256

/**
 * Default sustained-frame count before an event starts. The web
 * prototype uses 15 frames at ~60 fps (≈250 ms).
 */
#define DEFAULT_SUSTAIN_FRAMES 15

#define SG_STATUS_OK 0

#define SG_STATUS_EVENT_READY 1

#define SG_STATUS_NULL_POINTER -1

#define SG_STATUS_INVALID_LENGTH -2

#define SG_STATUS_INVALID_ARGUMENT -3

enum SgSensitivity {
  Low = 0,
  Medium = 1,
  High = 2,
};
typedef uint8_t SgSensitivity;

/**
 * Opaque handle. Swift sees this as a forward-declared struct and
 * only ever holds it via pointer.
 */
typedef struct SgDetector SgDetector;

typedef struct SgEvent {
  uint64_t start_ms;
  uint32_t duration_ms;
  float avg_db;
} SgEvent;

/**
 * Construct a detector. Returns NULL on invalid arguments
 * (`sample_rate_hz == 0`, or `threshold_db` non-finite) or if the
 * underlying allocation fails.
 */
struct SgDetector *sg_detector_new(float threshold_db,
                                   SgSensitivity sensitivity,
                                   uint32_t sample_rate_hz);

/**
 * Free a detector previously returned by [`sg_detector_new`].
 * Calling with NULL is a no-op.
 */
void sg_detector_free(struct SgDetector *d);

/**
 * Push one audio frame. `samples` must point to exactly
 * [`crate::FRAME_SIZE`] (256) `f32` values.
 *
 * Returns:
 * - `SG_STATUS_EVENT_READY` (1) if a new event was finalized — the
 *   caller should immediately call [`sg_detector_poll_event`] to read
 *   it before pushing more frames.
 * - `SG_STATUS_OK` (0) on a successful push without an event.
 * - Negative `SG_STATUS_*` on input error.
 */
int32_t sg_detector_push_frame(struct SgDetector *d, const float *samples, uintptr_t len);

/**
 * Drain the most-recent finalized event, if any.
 *
 * Returns 1 and writes into `*out` if an event was available, 0 if
 * none, negative on error.
 */
int32_t sg_detector_poll_event(struct SgDetector *d, struct SgEvent *out);

/**
 * Flush any in-flight event. Call when the caller stops pushing
 * frames (e.g. user stopped recording mid-snore) so the active event
 * isn't silently dropped.
 *
 * Returns 1 and writes the event into `*out` when one was in flight;
 * 0 when the detector was idle; negative `SG_STATUS_*` on error.
 * Mirrors the convention of [`sg_detector_poll_event`].
 */
int32_t sg_detector_finish(struct SgDetector *d, struct SgEvent *out);

int32_t sg_detector_set_threshold(struct SgDetector *d, float threshold_db);

int32_t sg_detector_set_sensitivity(struct SgDetector *d, SgSensitivity sensitivity);

/**
 * Frame size required by [`sg_detector_push_frame`].
 */
uintptr_t sg_frame_size(void);

#endif  /* SNOREGUARD_CORE_H */
